/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TornarPrestadorRouteImport } from './routes/tornar-prestador'
import { Route as TelasRouteImport } from './routes/telas'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NovoPedidoRouteImport } from './routes/novo-pedido'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as ProPedidosRouteImport } from './routes/pro.pedidos'
import { Route as ProOportunidadesRouteImport } from './routes/pro.oportunidades'
import { Route as ProGanhosRouteImport } from './routes/pro.ganhos'
import { Route as ProAgendaRouteImport } from './routes/pro.agenda'
import { Route as PrestadorIdRouteImport } from './routes/prestador.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TornarPrestadorRoute = TornarPrestadorRouteImport.update({
  id: '/tornar-prestador',
  path: '/tornar-prestador',
  getParentRoute: () => rootRouteImport,
} as any)
const TelasRoute = TelasRouteImport.update({
  id: '/telas',
  path: '/telas',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPedidoRoute = NovoPedidoRouteImport.update({
  id: '/novo-pedido',
  path: '/novo-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPedidosRoute = ProPedidosRouteImport.update({
  id: '/pro/pedidos',
  path: '/pro/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProOportunidadesRoute = ProOportunidadesRouteImport.update({
  id: '/pro/oportunidades',
  path: '/pro/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ProGanhosRoute = ProGanhosRouteImport.update({
  id: '/pro/ganhos',
  path: '/pro/ganhos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAgendaRoute = ProAgendaRouteImport.update({
  id: '/pro/agenda',
  path: '/pro/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadorIdRoute = PrestadorIdRouteImport.update({
  id: '/prestador/$id',
  path: '/prestador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/categorias/$slug',
  path: '/categorias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/carteira': typeof CarteiraRoute
  '/favoritos': typeof FavoritosRoute
  '/mcp': typeof McpRoute
  '/notificacoes': typeof NotificacoesRoute
  '/novo-pedido': typeof NovoPedidoRoute
  '/onboarding': typeof OnboardingRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/splash': typeof SplashRoute
  '/telas': typeof TelasRoute
  '/tornar-prestador': typeof TornarPrestadorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/chat/$id': typeof ChatIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/prestador/$id': typeof PrestadorIdRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/ganhos': typeof ProGanhosRoute
  '/pro/oportunidades': typeof ProOportunidadesRoute
  '/pro/pedidos': typeof ProPedidosRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/pro/': typeof ProIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/carteira': typeof CarteiraRoute
  '/favoritos': typeof FavoritosRoute
  '/mcp': typeof McpRoute
  '/notificacoes': typeof NotificacoesRoute
  '/novo-pedido': typeof NovoPedidoRoute
  '/onboarding': typeof OnboardingRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/splash': typeof SplashRoute
  '/telas': typeof TelasRoute
  '/tornar-prestador': typeof TornarPrestadorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/chat/$id': typeof ChatIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/prestador/$id': typeof PrestadorIdRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/ganhos': typeof ProGanhosRoute
  '/pro/oportunidades': typeof ProOportunidadesRoute
  '/pro/pedidos': typeof ProPedidosRoute
  '/categorias': typeof CategoriasIndexRoute
  '/chat': typeof ChatIndexRoute
  '/pro': typeof ProIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/carteira': typeof CarteiraRoute
  '/favoritos': typeof FavoritosRoute
  '/mcp': typeof McpRoute
  '/notificacoes': typeof NotificacoesRoute
  '/novo-pedido': typeof NovoPedidoRoute
  '/onboarding': typeof OnboardingRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/splash': typeof SplashRoute
  '/telas': typeof TelasRoute
  '/tornar-prestador': typeof TornarPrestadorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/chat/$id': typeof ChatIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/prestador/$id': typeof PrestadorIdRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/ganhos': typeof ProGanhosRoute
  '/pro/oportunidades': typeof ProOportunidadesRoute
  '/pro/pedidos': typeof ProPedidosRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/pro/': typeof ProIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/auth'
    | '/carteira'
    | '/favoritos'
    | '/mcp'
    | '/notificacoes'
    | '/novo-pedido'
    | '/onboarding'
    | '/pedidos'
    | '/perfil'
    | '/splash'
    | '/telas'
    | '/tornar-prestador'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categorias/$slug'
    | '/chat/$id'
    | '/pedido/$id'
    | '/prestador/$id'
    | '/pro/agenda'
    | '/pro/ganhos'
    | '/pro/oportunidades'
    | '/pro/pedidos'
    | '/categorias/'
    | '/chat/'
    | '/pro/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/auth'
    | '/carteira'
    | '/favoritos'
    | '/mcp'
    | '/notificacoes'
    | '/novo-pedido'
    | '/onboarding'
    | '/pedidos'
    | '/perfil'
    | '/splash'
    | '/telas'
    | '/tornar-prestador'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categorias/$slug'
    | '/chat/$id'
    | '/pedido/$id'
    | '/prestador/$id'
    | '/pro/agenda'
    | '/pro/ganhos'
    | '/pro/oportunidades'
    | '/pro/pedidos'
    | '/categorias'
    | '/chat'
    | '/pro'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/auth'
    | '/carteira'
    | '/favoritos'
    | '/mcp'
    | '/notificacoes'
    | '/novo-pedido'
    | '/onboarding'
    | '/pedidos'
    | '/perfil'
    | '/splash'
    | '/telas'
    | '/tornar-prestador'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categorias/$slug'
    | '/chat/$id'
    | '/pedido/$id'
    | '/prestador/$id'
    | '/pro/agenda'
    | '/pro/ganhos'
    | '/pro/oportunidades'
    | '/pro/pedidos'
    | '/categorias/'
    | '/chat/'
    | '/pro/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  AuthRoute: typeof AuthRoute
  CarteiraRoute: typeof CarteiraRoute
  FavoritosRoute: typeof FavoritosRoute
  McpRoute: typeof McpRoute
  NotificacoesRoute: typeof NotificacoesRoute
  NovoPedidoRoute: typeof NovoPedidoRoute
  OnboardingRoute: typeof OnboardingRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  SplashRoute: typeof SplashRoute
  TelasRoute: typeof TelasRoute
  TornarPrestadorRoute: typeof TornarPrestadorRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  ChatIdRoute: typeof ChatIdRoute
  PedidoIdRoute: typeof PedidoIdRoute
  PrestadorIdRoute: typeof PrestadorIdRoute
  ProAgendaRoute: typeof ProAgendaRoute
  ProGanhosRoute: typeof ProGanhosRoute
  ProOportunidadesRoute: typeof ProOportunidadesRoute
  ProPedidosRoute: typeof ProPedidosRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ProIndexRoute: typeof ProIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tornar-prestador': {
      id: '/tornar-prestador'
      path: '/tornar-prestador'
      fullPath: '/tornar-prestador'
      preLoaderRoute: typeof TornarPrestadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telas': {
      id: '/telas'
      path: '/telas'
      fullPath: '/telas'
      preLoaderRoute: typeof TelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-pedido': {
      id: '/novo-pedido'
      path: '/novo-pedido'
      fullPath: '/novo-pedido'
      preLoaderRoute: typeof NovoPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/pedidos': {
      id: '/pro/pedidos'
      path: '/pro/pedidos'
      fullPath: '/pro/pedidos'
      preLoaderRoute: typeof ProPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/oportunidades': {
      id: '/pro/oportunidades'
      path: '/pro/oportunidades'
      fullPath: '/pro/oportunidades'
      preLoaderRoute: typeof ProOportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/ganhos': {
      id: '/pro/ganhos'
      path: '/pro/ganhos'
      fullPath: '/pro/ganhos'
      preLoaderRoute: typeof ProGanhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/agenda': {
      id: '/pro/agenda'
      path: '/pro/agenda'
      fullPath: '/pro/agenda'
      preLoaderRoute: typeof ProAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestador/$id': {
      id: '/prestador/$id'
      path: '/prestador/$id'
      fullPath: '/prestador/$id'
      preLoaderRoute: typeof PrestadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/categorias/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  AuthRoute: AuthRoute,
  CarteiraRoute: CarteiraRoute,
  FavoritosRoute: FavoritosRoute,
  McpRoute: McpRoute,
  NotificacoesRoute: NotificacoesRoute,
  NovoPedidoRoute: NovoPedidoRoute,
  OnboardingRoute: OnboardingRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  SplashRoute: SplashRoute,
  TelasRoute: TelasRoute,
  TornarPrestadorRoute: TornarPrestadorRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CategoriasSlugRoute: CategoriasSlugRoute,
  ChatIdRoute: ChatIdRoute,
  PedidoIdRoute: PedidoIdRoute,
  PrestadorIdRoute: PrestadorIdRoute,
  ProAgendaRoute: ProAgendaRoute,
  ProGanhosRoute: ProGanhosRoute,
  ProOportunidadesRoute: ProOportunidadesRoute,
  ProPedidosRoute: ProPedidosRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ProIndexRoute: ProIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
